### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by selfus** [tuxmouraille/syncthing_ynh#7]
Hi,

I am trying to set up syncthing on my server, and would like to know if this project is still being maintained, because on yunohost page it is listed as not working.

**Comment by tuxmouraille** [comment]
This project is currently not maintained, because it doesn't need. It is usable like this.
I have corrected bug, only.

It need backup and restore scripts to be finish.

I want to add multi-instances supports, but I have no time for that.

**Comment by Zykino** [comment]
I may be wrong but doesn't YUNH team prefer when an app is tested and "certified" against a certain version of a software?
Can you add to the readme those information (if they are true since it's what I understand):
 - App should work whatever the version of YUNH and Syncthing are.
 - Syncthing is updated regularly by YUNH even if this repo is not up to date
 - Advanced: the config file of syncthing can be found _<path>_

**Comment by tuxmouraille** [comment]
Hello,
This package is not maintained, any more.
